// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SISTEMA_WEB___TIENDA.Data;

#nullable disable

namespace SISTEMA_WEB___TIENDA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701055220_ActualizaciónEstructura")]
    partial class ActualizaciónEstructura
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            NombreCategoria = "Casacas"
                        },
                        new
                        {
                            CategoriaId = 2,
                            NombreCategoria = "Polos"
                        },
                        new
                        {
                            CategoriaId = 3,
                            NombreCategoria = "Pantalones"
                        },
                        new
                        {
                            CategoriaId = 4,
                            NombreCategoria = "Vestidos"
                        },
                        new
                        {
                            CategoriaId = 5,
                            NombreCategoria = "Accesorios"
                        });
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.Ciudad", b =>
                {
                    b.Property<int>("CiudadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CiudadId"));

                    b.Property<string>("NombreCiudad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CiudadId");

                    b.ToTable("Ciudades");

                    b.HasData(
                        new
                        {
                            CiudadId = 1,
                            NombreCiudad = "Cajamarca"
                        });
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.Clientes", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<int>("CiudadId")
                        .HasColumnType("int");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("ClienteId");

                    b.HasIndex("CiudadId");

                    b.HasIndex("RolId");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            CiudadId = 1,
                            Contrasena = "$2a$11$dIhzGeX6bj/aLtA6W9SBIe.eq7waJlULyimU0VTFC87LQrnTWNoAK",
                            CorreoElectronico = "admin@aleanastore.com",
                            FechaNacimiento = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Administrador Aleana Store",
                            RolId = 1
                        },
                        new
                        {
                            ClienteId = 2,
                            CiudadId = 1,
                            Contrasena = "$2a$11$p45sXe/0Nm0WMRQFCeg7vuqwz6IBLLHW61bToDgBV7u1Wi5uxUFM6",
                            CorreoElectronico = "cajero@aleanastore.com",
                            FechaNacimiento = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Cajero Aleana Store",
                            RolId = 3
                        },
                        new
                        {
                            ClienteId = 3,
                            CiudadId = 1,
                            Contrasena = "$2a$11$o1xX0V900pVHmpGfM7TFwetAnzIwz58gzQQKA5IMi5Klyx8LibLSG",
                            CorreoElectronico = "cliente@aleanastore.com",
                            FechaNacimiento = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Cliente Prueba",
                            RolId = 2
                        });
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.DetallePedido", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VarianteId")
                        .HasColumnType("int");

                    b.HasKey("DetalleId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("VarianteId");

                    b.ToTable("DetallesPedido");
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.DireccionEnvio", b =>
                {
                    b.Property<int>("DireccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DireccionId"));

                    b.Property<string>("CalleAvenida")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ClientesId")
                        .HasColumnType("int");

                    b.Property<string>("Distrito")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("DireccionId");

                    b.HasIndex("ClientesId");

                    b.ToTable("DireccionesEnvio");

                    b.HasData(
                        new
                        {
                            DireccionId = 1,
                            CalleAvenida = "Jr. Principal 123",
                            ClientesId = 1,
                            Distrito = "Cajamarca",
                            Referencia = "Dirección por defecto"
                        });
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.EstadoPedido", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoId"));

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("EstadoId");

                    b.ToTable("EstadosPedido");

                    b.HasData(
                        new
                        {
                            EstadoId = 1,
                            NombreEstado = "Pendiente"
                        },
                        new
                        {
                            EstadoId = 2,
                            NombreEstado = "Confirmado"
                        },
                        new
                        {
                            EstadoId = 3,
                            NombreEstado = "En camino"
                        },
                        new
                        {
                            EstadoId = 4,
                            NombreEstado = "Entregado"
                        },
                        new
                        {
                            EstadoId = 5,
                            NombreEstado = "Cancelado"
                        });
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.Marca", b =>
                {
                    b.Property<int>("MarcaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarcaId"));

                    b.Property<string>("NombreMarca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MarcaId");

                    b.ToTable("Marcas");

                    b.HasData(
                        new
                        {
                            MarcaId = 1,
                            NombreMarca = "Aleana"
                        },
                        new
                        {
                            MarcaId = 2,
                            NombreMarca = "Sin Marca"
                        });
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.MetodoPago", b =>
                {
                    b.Property<int>("MetodoPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetodoPagoId"));

                    b.Property<string>("DescripcionPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MetodoPagoId");

                    b.ToTable("MetodosPago");

                    b.HasData(
                        new
                        {
                            MetodoPagoId = 1,
                            DescripcionPago = "Yape / Plin"
                        },
                        new
                        {
                            MetodoPagoId = 2,
                            DescripcionPago = "Tarjeta"
                        },
                        new
                        {
                            MetodoPagoId = 3,
                            DescripcionPago = "Efectivo"
                        });
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PedidoId"));

                    b.Property<int?>("CajeroId")
                        .HasColumnType("int");

                    b.Property<int>("ClientesId")
                        .HasColumnType("int");

                    b.Property<int>("DireccionId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCompra")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PedidoId");

                    b.HasIndex("CajeroId");

                    b.HasIndex("ClientesId");

                    b.HasIndex("DireccionId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("MetodoPagoId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.Prenda", b =>
                {
                    b.Property<int>("PrendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrendaId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagenPrincipalUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("NombrePrenda")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PrecioLista")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PrecioOferta")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PrendaId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("MarcaId");

                    b.ToTable("Prendas");
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.Proveedor", b =>
                {
                    b.Property<int>("ProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProveedorId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Contacto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RUC")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ProveedorId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.RegistroCaja", b =>
                {
                    b.Property<int>("RegistroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistroId"));

                    b.Property<int>("ClientesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MontoFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RegistroId");

                    b.HasIndex("ClientesId");

                    b.ToTable("RegistrosCaja");
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.Roles", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("RolId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            NombreRol = "Administrador"
                        },
                        new
                        {
                            RolId = 2,
                            NombreRol = "Cliente"
                        },
                        new
                        {
                            RolId = 3,
                            NombreRol = "Cajero"
                        });
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.VariantePrenda", b =>
                {
                    b.Property<int>("VarianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VarianteId"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("PrendaId")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("VarianteId");

                    b.HasIndex("PrendaId");

                    b.ToTable("VariantesPrenda");
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.Clientes", b =>
                {
                    b.HasOne("SISTEMA_WEB___TIENDA.Models.Ciudad", "Ciudad")
                        .WithMany("Clientes")
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SISTEMA_WEB___TIENDA.Models.Roles", "Rol")
                        .WithMany("Clientes")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciudad");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.DetallePedido", b =>
                {
                    b.HasOne("SISTEMA_WEB___TIENDA.Models.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SISTEMA_WEB___TIENDA.Models.VariantePrenda", "Variante")
                        .WithMany("DetallesPedido")
                        .HasForeignKey("VarianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Variante");
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.DireccionEnvio", b =>
                {
                    b.HasOne("SISTEMA_WEB___TIENDA.Models.Clientes", "Clientes")
                        .WithMany("Direcciones")
                        .HasForeignKey("ClientesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.Pedido", b =>
                {
                    b.HasOne("SISTEMA_WEB___TIENDA.Models.Clientes", "Cajero")
                        .WithMany()
                        .HasForeignKey("CajeroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SISTEMA_WEB___TIENDA.Models.Clientes", "Clientes")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClientesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SISTEMA_WEB___TIENDA.Models.DireccionEnvio", "DireccionEnvio")
                        .WithMany("Pedidos")
                        .HasForeignKey("DireccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SISTEMA_WEB___TIENDA.Models.EstadoPedido", "Estado")
                        .WithMany("Pedidos")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SISTEMA_WEB___TIENDA.Models.MetodoPago", "MetodoPago")
                        .WithMany("Pedidos")
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cajero");

                    b.Navigation("Clientes");

                    b.Navigation("DireccionEnvio");

                    b.Navigation("Estado");

                    b.Navigation("MetodoPago");
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.Prenda", b =>
                {
                    b.HasOne("SISTEMA_WEB___TIENDA.Models.Categoria", "Categoria")
                        .WithMany("Prendas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SISTEMA_WEB___TIENDA.Models.Marca", "Marca")
                        .WithMany("Prendas")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.Proveedor", b =>
                {
                    b.HasOne("SISTEMA_WEB___TIENDA.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.RegistroCaja", b =>
                {
                    b.HasOne("SISTEMA_WEB___TIENDA.Models.Clientes", "Cajero")
                        .WithMany()
                        .HasForeignKey("ClientesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cajero");
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.VariantePrenda", b =>
                {
                    b.HasOne("SISTEMA_WEB___TIENDA.Models.Prenda", "Prenda")
                        .WithMany("Variantes")
                        .HasForeignKey("PrendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prenda");
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.Categoria", b =>
                {
                    b.Navigation("Prendas");
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.Ciudad", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.Clientes", b =>
                {
                    b.Navigation("Direcciones");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.DireccionEnvio", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.EstadoPedido", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.Marca", b =>
                {
                    b.Navigation("Prendas");
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.MetodoPago", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.Pedido", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.Prenda", b =>
                {
                    b.Navigation("Variantes");
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.Roles", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("SISTEMA_WEB___TIENDA.Models.VariantePrenda", b =>
                {
                    b.Navigation("DetallesPedido");
                });
#pragma warning restore 612, 618
        }
    }
}
